### ISSUE TITLE
[TASK] Seapath ROS2 driver

### ISSUE THREAD

**Issue by EirikKolas** [vortexntnu/vortex-seapath-driver#1]
**Time estimate:** 12 hours

**Description of task:** Create a Seapath driver for ROS2

## Suggested Workflow
- [x] Get an overview of the existing driver
- [x] Find out why it doesn't give heading. This should be debugged by the company who provided the system

## Specs
- [x] Publish position as [sensormsgs/msg/NavSatFix](https://github.com/ros2/common_interfaces/blob/master/sensor_msgs/msg/NavSatFix.msg) 
- [x] Publish position relative to starting point
- [x] Option to reset starting point
- [x] ROS node should give errors/warnings if not connected

## Contacts
- @chrstrom - Mentor, made the first driver

**Comment by EirikKolas** [comment]
The warnings/status can be published on a [diagnostic_msgs](https://github.com/ros2/common_interfaces/tree/master/diagnostic_msgs) topic so that you can view it easily in [Foxglove Studio](https://foxglove.dev/docs/studio/panels/diagnostics)

**Comment by sondrtve** [comment]
Okay, will fix it later today!
________________________________
Fra: Eirik Kolås ***@***.***>
Sendt: fredag 13. oktober 2023 15:38
Til: vortexntnu/vortex-seapath-driver ***@***.***>
Kopi: Sondre Tveiten ***@***.***>; Assign ***@***.***>
Emne: Re: [vortexntnu/vortex-seapath-driver] [TASK] Seapath ROS2 driver (Issue #1)


The warnings/status can be published on a diagnostic_msgs<https://github.com/ros2/common_interfaces/tree/master/diagnostic_msgs> topic so that you can view it easily in Foxglove Studio<https://foxglove.dev/docs/studio/panels/diagnostics>
